---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: happysmile-individual
  namespace: happysmile
  labels:
    environment: production
spec:
  template:
    metadata:
      labels:
        app: happysmile-individual
    spec:
      containers:
      - name: happysmile-individual
        image: registry.digitalocean.com/searchcombat/happysmile-individual:sha-97d2da9
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: 500m
            memory: 600Mi
          limits:
            cpu: 600m
            memory: 600Mi
  replicas: 1
  selector:
    matchLabels:
      app: happysmile-individual
---
apiVersion: v1
kind: Service
metadata:
  name: happysmile-individual
  namespace: happysmile
  labels:
    environment: production
spec:
  type: ClusterIP
  selector:
    app: happysmile-individual
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: happysmile-individual
  namespace: happysmile
  labels:
    environment: production
spec:
  secretName: happysmile-individual
  issuerRef:
    name: letsencrypt-http
    kind: ClusterIssuer
  dnsNames:
  - happysmile.webdrift.ai
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: happysmile-individual
  namespace: happysmile
  labels:
    environment: production
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - happysmile.webdrift.ai
      secretName: happysmile-individual
  rules:
    - host: happysmile.webdrift.ai
      http:
        paths:
          - path: /?(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: happysmile-individual
                port:
                  number: 80